BEGIN;

COMMENT ON SCHEMA iam IS '身份认证、组织、成员角色、访问申请和权限审计数据';
COMMENT ON SCHEMA knowledge IS '连接器、会话采集、消息、附件、知识条目和可靠事件数据';
COMMENT ON SCHEMA rag IS '文档处理、检索索引、搜索和问答数据';

-- IAM

COMMENT ON TABLE iam.users IS '保存系统内部用户主体和基本资料';
COMMENT ON COLUMN iam.users.id IS '全局用户 ID';
COMMENT ON COLUMN iam.users.email IS '注册和登录邮箱';
COMMENT ON COLUMN iam.users.nickname IS '用户昵称';
COMMENT ON COLUMN iam.users.avatar_object_key IS '头像对象存储键';
COMMENT ON COLUMN iam.users.status IS '用户状态：pending、active、disabled';
COMMENT ON COLUMN iam.users.email_verified_at IS '邮箱验证时间';
COMMENT ON COLUMN iam.users.created_at IS '创建时间';
COMMENT ON COLUMN iam.users.updated_at IS '更新时间';
COMMENT ON COLUMN iam.users.deleted_at IS '注销或软删除时间';

COMMENT ON TABLE iam.user_credentials IS '保存密码及后续 OIDC、SSO 登录凭证，不保存明文密码';
COMMENT ON COLUMN iam.user_credentials.id IS '凭证 ID';
COMMENT ON COLUMN iam.user_credentials.user_id IS '所属用户 ID';
COMMENT ON COLUMN iam.user_credentials.credential_type IS '凭证类型：password、oidc、sso';
COMMENT ON COLUMN iam.user_credentials.credential_key IS '邮箱或外部主体标识';
COMMENT ON COLUMN iam.user_credentials.password_hash IS 'Argon2id 或 bcrypt 密码哈希';
COMMENT ON COLUMN iam.user_credentials.status IS '凭证状态：active、disabled';
COMMENT ON COLUMN iam.user_credentials.password_changed_at IS '最近密码变更时间';
COMMENT ON COLUMN iam.user_credentials.created_at IS '创建时间';
COMMENT ON COLUMN iam.user_credentials.updated_at IS '更新时间';

COMMENT ON TABLE iam.organizations IS '保存组织主体，Owner 由成员角色表达';
COMMENT ON COLUMN iam.organizations.id IS '组织 ID';
COMMENT ON COLUMN iam.organizations.name IS '组织名称';
COMMENT ON COLUMN iam.organizations.slug IS '组织可读唯一标识';
COMMENT ON COLUMN iam.organizations.status IS '组织状态：active、suspended、dissolved';
COMMENT ON COLUMN iam.organizations.created_by_user_id IS '最初创建人 ID，仅用于审计';
COMMENT ON COLUMN iam.organizations.created_at IS '创建时间';
COMMENT ON COLUMN iam.organizations.updated_at IS '更新时间';
COMMENT ON COLUMN iam.organizations.dissolved_at IS '组织解散时间';

COMMENT ON TABLE iam.organization_invitations IS '保存 Owner 或审批员创建的一次性组织邀请';
COMMENT ON COLUMN iam.organization_invitations.id IS '邀请 ID';
COMMENT ON COLUMN iam.organization_invitations.organization_id IS '目标组织 ID';
COMMENT ON COLUMN iam.organization_invitations.created_by_user_id IS '邀请创建人 ID';
COMMENT ON COLUMN iam.organization_invitations.token_hash IS '邀请令牌 SHA-256 哈希';
COMMENT ON COLUMN iam.organization_invitations.status IS '邀请状态：pending、accepted、revoked、expired';
COMMENT ON COLUMN iam.organization_invitations.expires_at IS '邀请过期时间';
COMMENT ON COLUMN iam.organization_invitations.accepted_by_user_id IS '邀请接受人 ID';
COMMENT ON COLUMN iam.organization_invitations.accepted_at IS '邀请接受时间';
COMMENT ON COLUMN iam.organization_invitations.revoked_by_user_id IS '邀请撤销人 ID';
COMMENT ON COLUMN iam.organization_invitations.revoked_at IS '邀请撤销时间';
COMMENT ON COLUMN iam.organization_invitations.created_at IS '创建时间';

COMMENT ON TABLE iam.organization_memberships IS '保存用户加入、暂停和退出组织的完整生命周期';
COMMENT ON COLUMN iam.organization_memberships.id IS '组织成员关系 ID';
COMMENT ON COLUMN iam.organization_memberships.organization_id IS '所属组织 ID';
COMMENT ON COLUMN iam.organization_memberships.user_id IS '成员用户 ID';
COMMENT ON COLUMN iam.organization_memberships.status IS '成员状态：active、suspended、leaving、left';
COMMENT ON COLUMN iam.organization_memberships.joined_via IS '加入方式：created、invitation';
COMMENT ON COLUMN iam.organization_memberships.invitation_id IS '加入组织所使用的邀请 ID';
COMMENT ON COLUMN iam.organization_memberships.joined_at IS '最近加入组织时间';
COMMENT ON COLUMN iam.organization_memberships.exit_reason IS '当前退出申请理由';
COMMENT ON COLUMN iam.organization_memberships.exit_requested_at IS '发起退出申请时间';
COMMENT ON COLUMN iam.organization_memberships.exit_reviewed_by_user_id IS '退出申请审批人 ID';
COMMENT ON COLUMN iam.organization_memberships.exit_review_note IS '退出申请审批说明';
COMMENT ON COLUMN iam.organization_memberships.exit_reviewed_at IS '退出申请审批时间';
COMMENT ON COLUMN iam.organization_memberships.left_at IS '获批退出组织时间';
COMMENT ON COLUMN iam.organization_memberships.suspended_at IS '成员暂停时间';
COMMENT ON COLUMN iam.organization_memberships.created_at IS '首次创建时间';
COMMENT ON COLUMN iam.organization_memberships.updated_at IS '更新时间';

COMMENT ON TABLE iam.membership_roles IS '保存组织成员固定角色，支持多角色和角色撤销';
COMMENT ON COLUMN iam.membership_roles.id IS '成员角色关系 ID';
COMMENT ON COLUMN iam.membership_roles.membership_id IS '组织成员关系 ID';
COMMENT ON COLUMN iam.membership_roles.role_code IS '固定角色代码';
COMMENT ON COLUMN iam.membership_roles.granted_by_user_id IS '角色授予人 ID';
COMMENT ON COLUMN iam.membership_roles.granted_at IS '角色授予时间';
COMMENT ON COLUMN iam.membership_roles.revoked_by_user_id IS '角色撤销人 ID';
COMMENT ON COLUMN iam.membership_roles.revoked_at IS '角色撤销时间，为空表示有效';

COMMENT ON TABLE iam.access_requests IS '保存受保护资源访问申请、审批、授权同步、有效期和撤销状态';
COMMENT ON COLUMN iam.access_requests.id IS '访问申请 ID';
COMMENT ON COLUMN iam.access_requests.organization_id IS '资源所属组织 ID，私人资源为空';
COMMENT ON COLUMN iam.access_requests.requester_user_id IS '申请人用户 ID';
COMMENT ON COLUMN iam.access_requests.resource_scope IS '资源范围：private、organization';
COMMENT ON COLUMN iam.access_requests.resource_type IS '资源类型：knowledge_original、attachment_content';
COMMENT ON COLUMN iam.access_requests.resource_id IS 'Knowledge 服务中的资源逻辑 ID';
COMMENT ON COLUMN iam.access_requests.action IS '申请动作：view、download';
COMMENT ON COLUMN iam.access_requests.reason IS '申请理由';
COMMENT ON COLUMN iam.access_requests.status IS '申请状态：pending、approved、rejected、cancelled、expired、revoked';
COMMENT ON COLUMN iam.access_requests.request_expires_at IS '待审批截止时间';
COMMENT ON COLUMN iam.access_requests.reviewed_by_user_id IS '审批人用户 ID';
COMMENT ON COLUMN iam.access_requests.reviewer_basis IS '审批资格来源：information_admin、collector';
COMMENT ON COLUMN iam.access_requests.review_note IS '审批说明';
COMMENT ON COLUMN iam.access_requests.reviewed_at IS '审批时间';
COMMENT ON COLUMN iam.access_requests.grant_expires_at IS '授权失效时间，为空表示长期';
COMMENT ON COLUMN iam.access_requests.fga_sync_status IS 'OpenFGA 同步状态：not_started、pending、synced、failed、removed';
COMMENT ON COLUMN iam.access_requests.fga_tuple_key IS 'OpenFGA 关系幂等键或追踪键';
COMMENT ON COLUMN iam.access_requests.granted_at IS '授权关系同步成功时间';
COMMENT ON COLUMN iam.access_requests.revoked_by_user_id IS '授权撤销人 ID';
COMMENT ON COLUMN iam.access_requests.revoked_at IS '授权撤销或过期清理时间';
COMMENT ON COLUMN iam.access_requests.last_error IS '最近一次同步错误';
COMMENT ON COLUMN iam.access_requests.created_at IS '创建时间';
COMMENT ON COLUMN iam.access_requests.updated_at IS '更新时间';

COMMENT ON TABLE iam.audit_logs IS '只追加保存登录、成员、角色、访问检查和资源访问等安全审计事件';
COMMENT ON COLUMN iam.audit_logs.id IS '审计记录 ID';
COMMENT ON COLUMN iam.audit_logs.actor_user_id IS '操作用户 ID，系统任务可为空';
COMMENT ON COLUMN iam.audit_logs.organization_id IS '操作发生时的组织上下文 ID';
COMMENT ON COLUMN iam.audit_logs.action IS '审计动作名称';
COMMENT ON COLUMN iam.audit_logs.resource_type IS '资源类型';
COMMENT ON COLUMN iam.audit_logs.resource_id IS '跨服务资源逻辑 ID';
COMMENT ON COLUMN iam.audit_logs.result IS '操作结果：success、failed、denied';
COMMENT ON COLUMN iam.audit_logs.request_id IS '链路请求 ID';
COMMENT ON COLUMN iam.audit_logs.ip_address IS '客户端 IP 地址';
COMMENT ON COLUMN iam.audit_logs.detail IS '审计扩展信息，禁止保存正文、密码和令牌';
COMMENT ON COLUMN iam.audit_logs.created_at IS '审计事件发生时间';

-- Knowledge

COMMENT ON TABLE knowledge.knowledge_bases IS '保存私人会话库、私人本地库、组织群聊库和公司文件库';
COMMENT ON COLUMN knowledge.knowledge_bases.id IS '知识库 ID';
COMMENT ON COLUMN knowledge.knowledge_bases.knowledge_scope IS '知识范围：private、organization';
COMMENT ON COLUMN knowledge.knowledge_bases.base_type IS '知识库类型：private_conversation、private_local、organization_conversation、organization_files';
COMMENT ON COLUMN knowledge.knowledge_bases.name IS '知识库展示名称';
COMMENT ON COLUMN knowledge.knowledge_bases.owner_user_id IS '私人知识库所有者用户逻辑 ID';
COMMENT ON COLUMN knowledge.knowledge_bases.organization_id IS '组织知识库所属组织逻辑 ID';
COMMENT ON COLUMN knowledge.knowledge_bases.source_key IS '会话接入 ID 等稳定来源键';
COMMENT ON COLUMN knowledge.knowledge_bases.status IS '知识库状态：active、archived';
COMMENT ON COLUMN knowledge.knowledge_bases.created_at IS '创建时间';
COMMENT ON COLUMN knowledge.knowledge_bases.updated_at IS '更新时间';

COMMENT ON TABLE knowledge.connector_accounts IS '保存内部用户绑定的飞书、企业微信和个人微信等外部账号';
COMMENT ON COLUMN knowledge.connector_accounts.id IS '连接器账号 ID';
COMMENT ON COLUMN knowledge.connector_accounts.owner_user_id IS '连接器所有者用户逻辑 ID';
COMMENT ON COLUMN knowledge.connector_accounts.platform IS '外部平台：feishu、wecom、wechat';
COMMENT ON COLUMN knowledge.connector_accounts.platform_workspace_key IS '外部平台企业或工作区标识，不是系统租户 ID';
COMMENT ON COLUMN knowledge.connector_accounts.external_account_id IS '外部账号 ID';
COMMENT ON COLUMN knowledge.connector_accounts.display_name IS '外部账号展示名称';
COMMENT ON COLUMN knowledge.connector_accounts.credential_ref IS 'KMS 或 Secret Manager 凭证引用，不保存明文令牌';
COMMENT ON COLUMN knowledge.connector_accounts.token_expires_at IS '外部平台令牌过期时间';
COMMENT ON COLUMN knowledge.connector_accounts.status IS '连接器状态：active、expired、revoked、error';
COMMENT ON COLUMN knowledge.connector_accounts.last_error IS '最近一次连接错误';
COMMENT ON COLUMN knowledge.connector_accounts.created_at IS '创建时间';
COMMENT ON COLUMN knowledge.connector_accounts.updated_at IS '更新时间';

COMMENT ON TABLE knowledge.external_identities IS '保存已接入会话中的外部联系人、发送人或群成员身份';
COMMENT ON COLUMN knowledge.external_identities.id IS '外部身份 ID';
COMMENT ON COLUMN knowledge.external_identities.platform IS '外部平台';
COMMENT ON COLUMN knowledge.external_identities.platform_workspace_key IS '外部平台企业或工作区标识，不是系统租户 ID';
COMMENT ON COLUMN knowledge.external_identities.external_user_id IS '平台用户 ID';
COMMENT ON COLUMN knowledge.external_identities.display_name IS '平台显示名称';
COMMENT ON COLUMN knowledge.external_identities.avatar_url IS '外部平台头像地址';
COMMENT ON COLUMN knowledge.external_identities.mapped_user_id IS '映射的内部用户逻辑 ID';
COMMENT ON COLUMN knowledge.external_identities.mapping_status IS '映射状态：unmapped、mapped、conflict';
COMMENT ON COLUMN knowledge.external_identities.mapped_at IS '映射完成时间';
COMMENT ON COLUMN knowledge.external_identities.created_at IS '创建时间';
COMMENT ON COLUMN knowledge.external_identities.updated_at IS '更新时间';

COMMENT ON TABLE knowledge.conversation_ingestions IS '保存用户确认后的私人会话采集或组织群聊接入';
COMMENT ON COLUMN knowledge.conversation_ingestions.id IS '会话接入 ID';
COMMENT ON COLUMN knowledge.conversation_ingestions.platform IS '外部平台：feishu、wecom、wechat';
COMMENT ON COLUMN knowledge.conversation_ingestions.platform_workspace_key IS '外部平台企业或工作区标识';
COMMENT ON COLUMN knowledge.conversation_ingestions.external_conversation_id IS '外部平台会话 ID';
COMMENT ON COLUMN knowledge.conversation_ingestions.conversation_type IS '会话类型：private、group';
COMMENT ON COLUMN knowledge.conversation_ingestions.name IS '接入时获取的会话名称';
COMMENT ON COLUMN knowledge.conversation_ingestions.avatar_url IS '接入时获取的会话头像地址';
COMMENT ON COLUMN knowledge.conversation_ingestions.platform_metadata IS '少量平台扩展元数据';
COMMENT ON COLUMN knowledge.conversation_ingestions.last_synced_at IS '会话元数据最近同步时间';
COMMENT ON COLUMN knowledge.conversation_ingestions.knowledge_base_id IS '目标知识库 ID';
COMMENT ON COLUMN knowledge.conversation_ingestions.ingestion_scope IS '接入范围：private、organization';
COMMENT ON COLUMN knowledge.conversation_ingestions.owner_user_id IS '私人接入所有者用户逻辑 ID';
COMMENT ON COLUMN knowledge.conversation_ingestions.organization_id IS '组织接入所属组织逻辑 ID';
COMMENT ON COLUMN knowledge.conversation_ingestions.created_by_user_id IS '发起接入的内部用户逻辑 ID';
COMMENT ON COLUMN knowledge.conversation_ingestions.requested_start_at IS '用户选择的采集起点';
COMMENT ON COLUMN knowledge.conversation_ingestions.effective_start_at IS '平台实际可采集起点';
COMMENT ON COLUMN knowledge.conversation_ingestions.permission_group_key IS '组织群聊对应的 OpenFGA conversation_group 键';
COMMENT ON COLUMN knowledge.conversation_ingestions.acl_version IS '权限事实版本';
COMMENT ON COLUMN knowledge.conversation_ingestions.status IS '接入状态：active、paused、detached、error';
COMMENT ON COLUMN knowledge.conversation_ingestions.pause_reason IS '暂停原因';
COMMENT ON COLUMN knowledge.conversation_ingestions.detached_by_user_id IS '解除接入的用户逻辑 ID';
COMMENT ON COLUMN knowledge.conversation_ingestions.detached_at IS '解除接入时间';
COMMENT ON COLUMN knowledge.conversation_ingestions.created_at IS '创建时间';
COMMENT ON COLUMN knowledge.conversation_ingestions.updated_at IS '更新时间';

COMMENT ON TABLE knowledge.conversation_memberships IS '保存已接入会话的平台成员动态有效期';
COMMENT ON COLUMN knowledge.conversation_memberships.id IS '会话成员关系 ID';
COMMENT ON COLUMN knowledge.conversation_memberships.conversation_ingestion_id IS '所属会话接入 ID';
COMMENT ON COLUMN knowledge.conversation_memberships.external_identity_id IS '外部成员身份 ID';
COMMENT ON COLUMN knowledge.conversation_memberships.member_role IS '平台群主、管理员或成员等角色';
COMMENT ON COLUMN knowledge.conversation_memberships.status IS '成员状态：active、left';
COMMENT ON COLUMN knowledge.conversation_memberships.joined_at IS '平台提供的加入时间';
COMMENT ON COLUMN knowledge.conversation_memberships.left_at IS '退出会话时间';
COMMENT ON COLUMN knowledge.conversation_memberships.last_seen_at IS '最近一次同步确认时间';
COMMENT ON COLUMN knowledge.conversation_memberships.created_at IS '创建时间';
COMMENT ON COLUMN knowledge.conversation_memberships.updated_at IS '更新时间';

COMMENT ON TABLE knowledge.conversation_collectors IS '保存会话主采集者、补充采集者及其采集检查点';
COMMENT ON COLUMN knowledge.conversation_collectors.id IS '采集者 ID';
COMMENT ON COLUMN knowledge.conversation_collectors.conversation_ingestion_id IS '所属会话接入 ID';
COMMENT ON COLUMN knowledge.conversation_collectors.connector_account_id IS '使用的个人连接器账号 ID';
COMMENT ON COLUMN knowledge.conversation_collectors.collector_user_id IS '连接器所属内部用户逻辑 ID 快照';
COMMENT ON COLUMN knowledge.conversation_collectors.collector_role IS '采集者角色：primary、supplemental';
COMMENT ON COLUMN knowledge.conversation_collectors.status IS '采集者状态：active、unavailable、removed';
COMMENT ON COLUMN knowledge.conversation_collectors.last_cursor IS '最近平台采集游标';
COMMENT ON COLUMN knowledge.conversation_collectors.last_success_at IS '最近成功采集时间';
COMMENT ON COLUMN knowledge.conversation_collectors.last_attempt_at IS '最近尝试采集时间';
COMMENT ON COLUMN knowledge.conversation_collectors.next_poll_at IS '下次轮询时间';
COMMENT ON COLUMN knowledge.conversation_collectors.consecutive_failures IS '连续失败次数';
COMMENT ON COLUMN knowledge.conversation_collectors.last_error IS '最近一次采集错误';
COMMENT ON COLUMN knowledge.conversation_collectors.joined_at IS '成为采集者时间';
COMMENT ON COLUMN knowledge.conversation_collectors.removed_at IS '采集者移除时间';
COMMENT ON COLUMN knowledge.conversation_collectors.created_at IS '创建时间';
COMMENT ON COLUMN knowledge.conversation_collectors.updated_at IS '更新时间';

COMMENT ON TABLE knowledge.messages IS '保存已接入会话中的统一规范化消息';
COMMENT ON COLUMN knowledge.messages.id IS '内部消息 ID';
COMMENT ON COLUMN knowledge.messages.conversation_ingestion_id IS '所属会话接入 ID';
COMMENT ON COLUMN knowledge.messages.external_message_id IS '外部平台消息 ID';
COMMENT ON COLUMN knowledge.messages.sender_identity_id IS '外部发送人身份 ID';
COMMENT ON COLUMN knowledge.messages.message_type IS '消息类型：text、image、file、mixed、system';
COMMENT ON COLUMN knowledge.messages.normalized_content_ref IS '规范化消息文本对象引用';
COMMENT ON COLUMN knowledge.messages.content_hash IS '统一消息内容 SHA-256 哈希';
COMMENT ON COLUMN knowledge.messages.content_version IS '消息内容版本，一期固定为 1';
COMMENT ON COLUMN knowledge.messages.sent_at IS '外部平台发送时间';
COMMENT ON COLUMN knowledge.messages.platform_updated_at IS '外部平台消息更新时间，为后续编辑预留';
COMMENT ON COLUMN knowledge.messages.lifecycle_status IS '消息生命周期状态，一期仅 active';
COMMENT ON COLUMN knowledge.messages.created_at IS '首次采集时间';

COMMENT ON TABLE knowledge.message_sources IS '保存同一消息被不同采集者观测到的来源记录';
COMMENT ON COLUMN knowledge.message_sources.id IS '消息来源记录 ID';
COMMENT ON COLUMN knowledge.message_sources.message_id IS '统一消息 ID';
COMMENT ON COLUMN knowledge.message_sources.collector_id IS '采集者 ID';
COMMENT ON COLUMN knowledge.message_sources.external_message_id IS '采集侧外部消息 ID';
COMMENT ON COLUMN knowledge.message_sources.raw_payload_ref IS '原始平台响应对象引用';
COMMENT ON COLUMN knowledge.message_sources.payload_hash IS '原始载荷哈希';
COMMENT ON COLUMN knowledge.message_sources.collected_at IS '采集时间';
COMMENT ON COLUMN knowledge.message_sources.created_at IS '创建时间';

COMMENT ON TABLE knowledge.attachments IS '保存群聊附件和本地上传文件的元数据、对象引用、处理及保护状态';
COMMENT ON COLUMN knowledge.attachments.id IS '附件 ID';
COMMENT ON COLUMN knowledge.attachments.request_id IS '本地上传请求幂等键，平台附件为空';
COMMENT ON COLUMN knowledge.attachments.message_id IS '群聊或私聊附件所属消息 ID';
COMMENT ON COLUMN knowledge.attachments.uploaded_by_user_id IS '本地上传人用户逻辑 ID';
COMMENT ON COLUMN knowledge.attachments.upload_destination IS '上传目标：private_local_library、organization_file_library';
COMMENT ON COLUMN knowledge.attachments.organization_id IS '附件所属组织逻辑 ID';
COMMENT ON COLUMN knowledge.attachments.file_name IS '文件名称';
COMMENT ON COLUMN knowledge.attachments.mime_type IS '文件 MIME 类型';
COMMENT ON COLUMN knowledge.attachments.size_bytes IS '文件大小，单位为字节';
COMMENT ON COLUMN knowledge.attachments.external_attachment_id IS '平台消息中的外部附件 ID，本地上传为空';
COMMENT ON COLUMN knowledge.attachments.object_ref IS '原附件对象引用，多个逻辑附件可复用同一物理对象';
COMMENT ON COLUMN knowledge.attachments.source_private_attachment_id IS '共享私人文件时指向原私人附件 ID';
COMMENT ON COLUMN knowledge.attachments.content_hash IS '文件内容 SHA-256 哈希';
COMMENT ON COLUMN knowledge.attachments.content_version IS '附件内容版本，一期固定为 1';
COMMENT ON COLUMN knowledge.attachments.metadata_access_scope IS '附件元数据基础访问范围';
COMMENT ON COLUMN knowledge.attachments.content_access_scope IS '附件内容基础访问范围';
COMMENT ON COLUMN knowledge.attachments.acl_version IS '附件权限事实版本';
COMMENT ON COLUMN knowledge.attachments.encrypted IS '对象是否加密保存';
COMMENT ON COLUMN knowledge.attachments.content_access_required IS '查看或下载附件内容是否需要显式授权';
COMMENT ON COLUMN knowledge.attachments.upload_status IS '上传状态：pending、validating、uploading、uploaded、failed、duplicate';
COMMENT ON COLUMN knowledge.attachments.upload_error IS '上传失败摘要';
COMMENT ON COLUMN knowledge.attachments.uploaded_at IS '对象存储写入完成时间';
COMMENT ON COLUMN knowledge.attachments.extracted_original_ref IS '原始解析文本引用，不进入普通索引';
COMMENT ON COLUMN knowledge.attachments.extracted_display_ref IS '可索引的普通或脱敏解析文本引用';
COMMENT ON COLUMN knowledge.attachments.processing_status IS '处理状态：pending、processing、ready、failed';
COMMENT ON COLUMN knowledge.attachments.sensitivity IS '敏感等级：public、internal、confidential、restricted';
COMMENT ON COLUMN knowledge.attachments.created_at IS '创建时间';
COMMENT ON COLUMN knowledge.attachments.updated_at IS '更新时间';

COMMENT ON TABLE knowledge.knowledge_items IS '保存供 IAM 和 RAG 使用的稳定知识资源、内容版本及处理状态';
COMMENT ON COLUMN knowledge.knowledge_items.id IS 'KnowledgeItem 资源 ID';
COMMENT ON COLUMN knowledge.knowledge_items.knowledge_base_id IS '所属知识库 ID';
COMMENT ON COLUMN knowledge.knowledge_items.knowledge_scope IS '知识范围：private、organization';
COMMENT ON COLUMN knowledge.knowledge_items.access_scope IS '访问范围：owner_only、organization_members、conversation_members';
COMMENT ON COLUMN knowledge.knowledge_items.owner_user_id IS '私人知识所有者用户逻辑 ID';
COMMENT ON COLUMN knowledge.knowledge_items.organization_id IS '组织知识所属组织逻辑 ID';
COMMENT ON COLUMN knowledge.knowledge_items.conversation_ingestion_id IS '群聊权限来源的会话接入 ID';
COMMENT ON COLUMN knowledge.knowledge_items.source_type IS '来源类型：platform_conversation、private_conversation、local_upload、shared_private_item';
COMMENT ON COLUMN knowledge.knowledge_items.source_message_id IS '来源消息 ID';
COMMENT ON COLUMN knowledge.knowledge_items.source_attachment_id IS '来源附件 ID';
COMMENT ON COLUMN knowledge.knowledge_items.source_private_item_id IS '共享私人知识的原 KnowledgeItem ID';
COMMENT ON COLUMN knowledge.knowledge_items.share_request_id IS '共享 API 请求幂等键';
COMMENT ON COLUMN knowledge.knowledge_items.share_batch_id IS '首次处理共享请求时生成的批次 ID';
COMMENT ON COLUMN knowledge.knowledge_items.shared_by_user_id IS '共享人用户逻辑 ID';
COMMENT ON COLUMN knowledge.knowledge_items.shared_at IS '共享时间';
COMMENT ON COLUMN knowledge.knowledge_items.content_type IS '内容类型：text、file、image、spreadsheet、mixed';
COMMENT ON COLUMN knowledge.knowledge_items.content_ref IS '对外展示的普通或脱敏内容引用';
COMMENT ON COLUMN knowledge.knowledge_items.original_content_ref IS '受保护原始内容引用';
COMMENT ON COLUMN knowledge.knowledge_items.content_hash IS '当前业务内容 SHA-256 哈希';
COMMENT ON COLUMN knowledge.knowledge_items.content_version IS '业务内容版本，一期固定为 1';
COMMENT ON COLUMN knowledge.knowledge_items.content_visibility IS '展示内容形态：original、masked、metadata_only';
COMMENT ON COLUMN knowledge.knowledge_items.original_access_required IS '查看原文是否需要显式授权';
COMMENT ON COLUMN knowledge.knowledge_items.security_status IS '安全处理状态：not_required、pending、processing、classified、failed';
COMMENT ON COLUMN knowledge.knowledge_items.sensitivity IS '敏感等级：public、internal、confidential、restricted';
COMMENT ON COLUMN knowledge.knowledge_items.security_policy_version IS '脱敏或分类策略版本';
COMMENT ON COLUMN knowledge.knowledge_items.content_saved IS '内容保存完成闸门';
COMMENT ON COLUMN knowledge.knowledge_items.ownership_ready IS '归属关系准备完成闸门';
COMMENT ON COLUMN knowledge.knowledge_items.security_ready IS '安全处理准备完成闸门';
COMMENT ON COLUMN knowledge.knowledge_items.permission_ready IS 'OpenFGA 权限关系准备完成闸门';
COMMENT ON COLUMN knowledge.knowledge_items.acl_version IS '资源权限事实版本';
COMMENT ON COLUMN knowledge.knowledge_items.acl_sync_status IS 'ACL 同步状态：not_required、pending、synced、failed';
COMMENT ON COLUMN knowledge.knowledge_items.processing_status IS 'RAG 处理状态：pending、published、processing、ready、failed';
COMMENT ON COLUMN knowledge.knowledge_items.lifecycle_status IS '知识生命周期状态，一期仅 active';
COMMENT ON COLUMN knowledge.knowledge_items.last_error IS '最近一次隐私、ACL 或发布错误';
COMMENT ON COLUMN knowledge.knowledge_items.created_at IS '创建时间';
COMMENT ON COLUMN knowledge.knowledge_items.updated_at IS '更新时间';

COMMENT ON TABLE knowledge.outbox_events IS '保存 Knowledge 服务待可靠发布的事务事件';
COMMENT ON COLUMN knowledge.outbox_events.id IS '事件 ID';
COMMENT ON COLUMN knowledge.outbox_events.aggregate_type IS '聚合类型';
COMMENT ON COLUMN knowledge.outbox_events.aggregate_id IS '聚合 ID';
COMMENT ON COLUMN knowledge.outbox_events.event_type IS '事件类型';
COMMENT ON COLUMN knowledge.outbox_events.event_version IS '同一聚合的事件版本';
COMMENT ON COLUMN knowledge.outbox_events.schema_version IS '事件载荷结构版本';
COMMENT ON COLUMN knowledge.outbox_events.organization_id IS '组织上下文逻辑 ID，私人知识为空';
COMMENT ON COLUMN knowledge.outbox_events.trace_id IS '链路追踪 ID';
COMMENT ON COLUMN knowledge.outbox_events.payload IS '稳定跨服务事件载荷，不保存大正文或二进制';
COMMENT ON COLUMN knowledge.outbox_events.status IS '发布状态：pending、publishing、published、failed';
COMMENT ON COLUMN knowledge.outbox_events.retry_count IS '发布重试次数';
COMMENT ON COLUMN knowledge.outbox_events.available_at IS '下次允许发布时间';
COMMENT ON COLUMN knowledge.outbox_events.published_at IS 'Redis Streams 发布成功时间';
COMMENT ON COLUMN knowledge.outbox_events.last_error IS '最近一次发布错误';
COMMENT ON COLUMN knowledge.outbox_events.created_at IS '创建时间';

COMMENT ON TABLE knowledge.private_share_requests IS '保存私聊批量共享请求指纹、批次状态和结果';
COMMENT ON COLUMN knowledge.private_share_requests.id IS '共享请求记录 ID';
COMMENT ON COLUMN knowledge.private_share_requests.requester_user_id IS '发起共享的用户逻辑 ID';
COMMENT ON COLUMN knowledge.private_share_requests.request_id IS '共享 API 请求幂等键';
COMMENT ON COLUMN knowledge.private_share_requests.request_fingerprint IS '私聊 ID 与规范化消息 ID 集合的 SHA-256 指纹';
COMMENT ON COLUMN knowledge.private_share_requests.private_conversation_id IS '被共享的私人会话接入 ID';
COMMENT ON COLUMN knowledge.private_share_requests.organization_id IS '首次处理时确定的目标组织逻辑 ID';
COMMENT ON COLUMN knowledge.private_share_requests.share_batch_id IS '首次处理请求时由服务端生成的共享批次 ID';
COMMENT ON COLUMN knowledge.private_share_requests.status IS '处理状态：processing、completed、failed';
COMMENT ON COLUMN knowledge.private_share_requests.shared_message_count IS '成功共享的消息数量';
COMMENT ON COLUMN knowledge.private_share_requests.shared_attachment_count IS '成功共享的附件数量';
COMMENT ON COLUMN knowledge.private_share_requests.last_error IS '最近一次失败摘要';
COMMENT ON COLUMN knowledge.private_share_requests.created_at IS '创建时间';
COMMENT ON COLUMN knowledge.private_share_requests.updated_at IS '更新时间';
COMMENT ON COLUMN knowledge.private_share_requests.completed_at IS '处理完成时间';

-- RAG

COMMENT ON TABLE rag.processing_jobs IS '保存事件消费幂等、文档解析、切块、向量化、索引和 ACL 刷新任务';
COMMENT ON COLUMN rag.processing_jobs.id IS '处理任务 ID';
COMMENT ON COLUMN rag.processing_jobs.source_event_id IS '来源事件 ID，作为至少一次投递的幂等键';
COMMENT ON COLUMN rag.processing_jobs.event_type IS '来源事件类型';
COMMENT ON COLUMN rag.processing_jobs.payload_hash IS '同一事件 ID 的载荷一致性校验哈希';
COMMENT ON COLUMN rag.processing_jobs.organization_id IS '组织上下文逻辑 ID';
COMMENT ON COLUMN rag.processing_jobs.knowledge_item_id IS 'KnowledgeItem 逻辑 ID';
COMMENT ON COLUMN rag.processing_jobs.content_version IS '任务对应的业务内容版本';
COMMENT ON COLUMN rag.processing_jobs.acl_version IS '任务对应的权限版本';
COMMENT ON COLUMN rag.processing_jobs.job_type IS '任务类型：preparse、full_process、reindex、acl_refresh、delete_index';
COMMENT ON COLUMN rag.processing_jobs.status IS '任务状态：pending、processing、succeeded、failed、dead';
COMMENT ON COLUMN rag.processing_jobs.current_stage IS '当前阶段：fetch、parse、chunk、embed、index';
COMMENT ON COLUMN rag.processing_jobs.parser_name IS '解析器名称';
COMMENT ON COLUMN rag.processing_jobs.parser_version IS '解析器版本';
COMMENT ON COLUMN rag.processing_jobs.parsed_artifact_ref IS '解析产物对象引用';
COMMENT ON COLUMN rag.processing_jobs.parsed_content_hash IS '解析产物内容 SHA-256 哈希';
COMMENT ON COLUMN rag.processing_jobs.page_count IS '文档页数';
COMMENT ON COLUMN rag.processing_jobs.chunking_version IS '切块配置版本';
COMMENT ON COLUMN rag.processing_jobs.embedding_model IS 'Embedding 模型名称及版本';
COMMENT ON COLUMN rag.processing_jobs.retry_count IS '任务重试次数';
COMMENT ON COLUMN rag.processing_jobs.available_at IS '下次允许执行时间';
COMMENT ON COLUMN rag.processing_jobs.started_at IS '任务开始时间';
COMMENT ON COLUMN rag.processing_jobs.finished_at IS '任务结束时间';
COMMENT ON COLUMN rag.processing_jobs.last_error IS '最近一次任务错误';
COMMENT ON COLUMN rag.processing_jobs.created_at IS '创建时间';

COMMENT ON TABLE rag.index_records IS '保存知识版本与 Elasticsearch 文档的映射及索引状态';
COMMENT ON COLUMN rag.index_records.id IS '索引记录 ID';
COMMENT ON COLUMN rag.index_records.knowledge_item_id IS 'KnowledgeItem 逻辑 ID';
COMMENT ON COLUMN rag.index_records.organization_id IS '组织范围过滤逻辑 ID';
COMMENT ON COLUMN rag.index_records.owner_user_id IS '私人知识所有者过滤逻辑 ID';
COMMENT ON COLUMN rag.index_records.content_version IS '已索引的业务内容版本';
COMMENT ON COLUMN rag.index_records.acl_version IS '已索引的 ACL 版本';
COMMENT ON COLUMN rag.index_records.content_variant IS 'ES 内容形态：display 或 protected，分别对应展示和受保护索引';
COMMENT ON COLUMN rag.index_records.es_index_alias IS 'Elasticsearch 读取别名';
COMMENT ON COLUMN rag.index_records.es_document_prefix IS 'Elasticsearch 切块文档 ID 前缀';
COMMENT ON COLUMN rag.index_records.chunk_count IS '已建立索引的切块数量';
COMMENT ON COLUMN rag.index_records.mapping_version IS 'Elasticsearch Mapping、分词和向量维度版本';
COMMENT ON COLUMN rag.index_records.status IS '索引状态：pending、indexing、ready、failed、deleted';
COMMENT ON COLUMN rag.index_records.indexed_at IS '索引完成时间';
COMMENT ON COLUMN rag.index_records.last_error IS '最近一次索引错误';
COMMENT ON COLUMN rag.index_records.created_at IS '创建时间';
COMMENT ON COLUMN rag.index_records.updated_at IS '更新时间';

COMMENT ON TABLE rag.search_history IS '保存搜索关键词、过滤条件和性能统计，不保存完整候选正文';
COMMENT ON COLUMN rag.search_history.id IS '搜索记录 ID';
COMMENT ON COLUMN rag.search_history.user_id IS '发起搜索的用户逻辑 ID';
COMMENT ON COLUMN rag.search_history.organization_id IS '组织上下文逻辑 ID，私人搜索为空';
COMMENT ON COLUMN rag.search_history.query_text IS '搜索词，按数据保留策略清理';
COMMENT ON COLUMN rag.search_history.query_hash IS '规范化搜索词哈希';
COMMENT ON COLUMN rag.search_history.filters IS '知识库、来源和时间等搜索过滤条件';
COMMENT ON COLUMN rag.search_history.result_count IS '权限过滤后的结果数量';
COMMENT ON COLUMN rag.search_history.duration_ms IS '搜索总耗时，单位为毫秒';
COMMENT ON COLUMN rag.search_history.request_id IS '链路请求 ID';
COMMENT ON COLUMN rag.search_history.created_at IS '搜索时间';

COMMENT ON TABLE rag.qa_conversations IS '保存用户 RAG 问答会话';
COMMENT ON COLUMN rag.qa_conversations.id IS '问答会话 ID';
COMMENT ON COLUMN rag.qa_conversations.user_id IS '所属用户逻辑 ID';
COMMENT ON COLUMN rag.qa_conversations.organization_id IS '组织上下文逻辑 ID';
COMMENT ON COLUMN rag.qa_conversations.title IS '问答会话标题';
COMMENT ON COLUMN rag.qa_conversations.status IS '会话状态：active、archived、deleted';
COMMENT ON COLUMN rag.qa_conversations.created_at IS '创建时间';
COMMENT ON COLUMN rag.qa_conversations.updated_at IS '更新时间';
COMMENT ON COLUMN rag.qa_conversations.deleted_at IS '软删除时间';

COMMENT ON TABLE rag.qa_messages IS '保存问答消息、生成元数据和当次引用';
COMMENT ON COLUMN rag.qa_messages.id IS '问答消息 ID';
COMMENT ON COLUMN rag.qa_messages.conversation_id IS '所属问答会话 ID';
COMMENT ON COLUMN rag.qa_messages.parent_message_id IS '父消息 ID，用于支持重新生成';
COMMENT ON COLUMN rag.qa_messages.role IS '消息角色：user、assistant、system';
COMMENT ON COLUMN rag.qa_messages.content IS '问题或回答正文，只允许包含已获准展示的内容';
COMMENT ON COLUMN rag.qa_messages.citations IS 'Assistant 回答引用数组';
COMMENT ON COLUMN rag.qa_messages.model_name IS '生成模型名称及版本';
COMMENT ON COLUMN rag.qa_messages.prompt_version IS 'Prompt 模板版本';
COMMENT ON COLUMN rag.qa_messages.status IS '消息状态：streaming、completed、failed、cancelled';
COMMENT ON COLUMN rag.qa_messages.token_usage IS '模型 Token 使用统计';
COMMENT ON COLUMN rag.qa_messages.duration_ms IS '生成耗时，单位为毫秒';
COMMENT ON COLUMN rag.qa_messages.error_message IS '生成失败摘要';
COMMENT ON COLUMN rag.qa_messages.created_at IS '创建时间';

COMMENT ON TABLE rag.outbox_events IS '保存 RAG 服务待可靠发布的解析和处理结果事务事件';
COMMENT ON COLUMN rag.outbox_events.id IS '事件 ID';
COMMENT ON COLUMN rag.outbox_events.aggregate_type IS '聚合类型';
COMMENT ON COLUMN rag.outbox_events.aggregate_id IS '聚合 ID';
COMMENT ON COLUMN rag.outbox_events.event_type IS '事件类型：document.extracted、processing.completed、processing.failed';
COMMENT ON COLUMN rag.outbox_events.event_version IS '同一聚合的事件版本';
COMMENT ON COLUMN rag.outbox_events.schema_version IS '事件载荷结构版本';
COMMENT ON COLUMN rag.outbox_events.organization_id IS '组织上下文逻辑 ID，私人任务为空';
COMMENT ON COLUMN rag.outbox_events.trace_id IS '链路追踪 ID';
COMMENT ON COLUMN rag.outbox_events.payload IS '稳定事件载荷，不保存二进制内容';
COMMENT ON COLUMN rag.outbox_events.status IS '发布状态：pending、publishing、published、failed';
COMMENT ON COLUMN rag.outbox_events.retry_count IS '发布重试次数';
COMMENT ON COLUMN rag.outbox_events.available_at IS '下次允许发布时间';
COMMENT ON COLUMN rag.outbox_events.published_at IS '事件发布时间';
COMMENT ON COLUMN rag.outbox_events.last_error IS '最近一次发布错误';
COMMENT ON COLUMN rag.outbox_events.created_at IS '创建时间';

COMMIT;
