<template>
  <section class="wk-page profile-page"><div class="profile-page__head"><div><h1>个人中心</h1><p>个人资料和第三方连接器</p></div><t-button theme="primary" @click="save"><template #icon><t-icon name="check" /></template>保存修改</t-button></div><div class="profile-layout"><div class="wk-settings-group"><div class="wk-setting-row wk-setting-row--profile"><div class="wk-profile-avatar">{{ profile.avatar }}</div><div class="wk-setting-info"><h2>个人资料</h2><p>昵称和头像仅用于你的私人工作台。</p></div><div class="wk-setting-control wk-profile-fields"><t-input v-model="profile.nickname" placeholder="昵称" /><t-input v-model="profile.avatar" maxlength="2" placeholder="头像文字（1-2 个字）" /><t-input v-model="profile.email" type="email" placeholder="邮箱" /></div></div><div class="wk-setting-row"><div class="wk-setting-info"><label>登录方式</label><p>当前仅支持邮箱和密码登录。</p></div><div class="wk-setting-control"><span class="wk-info-value">{{ profile.email }}</span></div></div><div class="wk-setting-row"><div class="wk-setting-info"><label>数据可见性</label><p>采集数据只允许本人查看，管理员默认不能查看私人数据。</p></div><div class="wk-setting-control"><t-tag theme="success" variant="light"><t-icon name="lock-on" /> 仅本人可见</t-tag></div></div></div><div class="wk-settings-group"><div class="wk-settings-group__title"><h2>连接器</h2><p>授权后开放对应知识库。一个外部账号只能绑定一个系统用户。</p></div><div v-for="source in sources" :key="source.key" class="wk-setting-row"><div class="wk-connector-icon" :style="{ background: sourceColor[source.key] }">{{ source.name.slice(0, 1) }}</div><div class="wk-setting-info"><label>{{ source.name }}</label><p>{{ source.bound ? source.account : '未绑定，绑定后可选择群聊并持续采集' }}</p></div><div class="wk-setting-control"><t-tag v-if="source.bound" theme="success" variant="light">已授权</t-tag><t-button :theme="source.bound ? 'default' : 'primary'" :variant="source.bound ? 'outline' : 'base'" size="small" @click="toggle(source)">{{ source.bound ? '解除绑定' : '绑定' }}</t-button></div></div></div></div></section>
</template>

<script setup lang="ts">
import type { InfoSource } from '../mock'
import { sourceColor } from '../mock'

const props = defineProps<{ sources: InfoSource[]; profile: { nickname: string; email: string; avatar: string } }>()
const emit = defineEmits<{ (event: 'toast', text: string): void }>()
function toggle(source: InfoSource) { source.bound = !source.bound; source.account = source.bound ? `林默 · ${source.name}` : ''; emit('toast', source.bound ? `已绑定${source.name}` : `已解除${source.name}绑定`) }
function save() { emit('toast', '个人资料已保存到本地') }
</script>

<style lang="less" scoped>
.wk-page { width: min(1120px, 100%); margin: 0 auto; padding: 30px 34px 56px; }.profile-page__head { display: flex; align-items: flex-end; justify-content: space-between; gap: 20px; margin-bottom: 27px; }.profile-page__head h1 { margin: 0 0 7px; font-size: 24px; font-weight: 600; }.profile-page__head p { margin: 0; color: var(--td-text-color-secondary); font-size: 13px; }.profile-layout { display: grid; grid-template-columns: 1fr; gap: 22px; }.wk-settings-group { overflow: hidden; border: 1px solid var(--td-component-stroke); border-radius: 8px; background: var(--td-bg-color-container); }.wk-settings-group__title { padding: 19px 20px 13px; border-bottom: 1px solid var(--td-component-stroke); }.wk-settings-group__title h2 { margin: 0 0 5px; font-size: 15px; }.wk-settings-group__title p { margin: 0; color: var(--td-text-color-secondary); font-size: 12px; }.wk-setting-row { display: flex; align-items: center; gap: 14px; min-height: 78px; padding: 16px 20px; border-bottom: 1px solid var(--td-component-stroke); }.wk-setting-row:last-child { border-bottom: 0; }.wk-setting-row--profile { align-items: flex-start; min-height: 110px; }.wk-profile-avatar { display: grid; place-items: center; width: 58px; height: 58px; flex: 0 0 58px; border-radius: 50%; color: #fff; background: var(--td-brand-color); font-size: 20px; font-weight: 600; }.wk-setting-info { flex: 1; min-width: 0; }.wk-setting-info h2, .wk-setting-info label { display: block; margin: 0 0 5px; color: var(--td-text-color-primary); font-size: 14px; font-weight: 500; }.wk-setting-info p { margin: 0; color: var(--td-text-color-secondary); font-size: 12px; line-height: 1.5; }.wk-setting-control { display: flex; align-items: center; justify-content: flex-end; gap: 9px; min-width: 250px; }.wk-profile-fields { flex-direction: column; align-items: stretch; width: 260px; min-width: 260px; }.wk-profile-fields :deep(.t-input) { width: 100%; }.wk-info-value { color: var(--td-text-color-secondary); font-size: 13px; }.wk-connector-icon { display: grid; place-items: center; width: 35px; height: 35px; flex: 0 0 35px; border-radius: 7px; color: #fff; font-size: 12px; font-weight: 600; }.wk-connector-icon + .wk-setting-info { margin-left: 1px; }.wk-setting-control :deep(.t-tag) { display: inline-flex; align-items: center; gap: 4px; }.wk-setting-control :deep(.t-tag svg) { width: 13px; }
@media (max-width: 760px) { .wk-page { padding: 22px 16px 45px; }.profile-page__head { align-items: flex-start; flex-direction: column; }.wk-setting-row, .wk-setting-row--profile { align-items: flex-start; flex-wrap: wrap; }.wk-setting-control, .wk-profile-fields { width: 100%; min-width: 0; justify-content: flex-start; }.wk-profile-avatar { width: 48px; height: 48px; flex-basis: 48px; font-size: 16px; }}
</style>
