events {}

http {
    map $http_x_request_id $upstream_request_id {
        default $http_x_request_id;
        ""      $request_id;
    }
    map $http_x_trace_id $upstream_trace_id {
        default $http_x_trace_id;
        ""      $request_id;
    }
    include conf.d/*.conf;
}
