<template>
  <section class="contacts-page">
    <div class="contacts-head"><div><h1>联系人列表</h1><p>管理已接入的微信和飞书联系人</p></div><div class="actions"><t-select v-model="platform" clearable placeholder="全部平台" :options="platformOptions" /><t-button theme="primary" @click="showAttach = true">接入联系人</t-button></div></div>
    <t-alert v-if="error" theme="error" :message="error" />
    <div v-if="loading" class="state">正在加载联系人…</div>
    <div v-else-if="!contacts.length" class="state empty"><t-icon name="usergroup" /><strong>暂无联系人</strong><span>接入微信或飞书联系人后，他们会显示在这里</span></div>
    <div v-else class="contact-grid"><article v-for="contact in contacts" :key="contact.id" class="contact-card" @click="openDetail(contact)"><div class="avatar">{{ (contact.display_name || contact.identities[0]?.display_name || '?').slice(0,1) }}</div><div class="contact-main"><h3>{{ contact.display_name || contact.identities[0]?.display_name || '未命名联系人' }}</h3><span class="kind">{{ contact.kind === 'internal' ? '内部联系人' : '外部联系人' }}</span><div class="identity-list"><span v-for="identity in contact.identities" :key="identity.id" class="identity"><t-icon :name="identity.platform === 'feishu' ? 'logo-feishu' : 'logo-wechat'" />{{ identity.platform === 'feishu' ? '飞书' : '微信' }} · {{ identity.external_user_id }}</span></div></div></article></div>
    <t-dialog v-model:visible="showAttach" header="接入联系人" :confirm-btn="null" width="620px"><t-space direction="vertical" style="width:100%"><t-select v-model="attachPlatform" :options="platformOptions" placeholder="选择平台账号" @change="discover" /><t-input v-model="query" placeholder="搜索姓名或账号" clearable @enter="discover" /><t-loading :loading="discovering"><div class="discover-list"><div v-for="item in available" :key="item.external_user_id" class="discover-item"><span>{{ item.display_name || item.external_user_id }}</span><small>{{ item.external_user_id }}</small><t-button size="small" :disabled="item.selected" @click="attach(item)">{{ item.selected ? '已接入' : '接入' }}</t-button></div><span v-if="!available.length">暂无可接入联系人</span></div></t-loading></t-space></t-dialog>
    <t-dialog v-model:visible="showDetail" header="联系人详情" :confirm-btn="null"><div v-if="detail"><p><strong>{{ detail.display_name || '未命名联系人' }}</strong></p><p>消息 {{ detail.messages?.length || 0 }} 条，附件引用 {{ detail.attachments?.length || 0 }} 个</p><t-button theme="danger" variant="outline" @click="remove">移除联系人</t-button></div></t-dialog>
  </section>
</template>
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { listContacts, discoverContacts, attachContact, removeContact, getContact, type ContactDTO, type AvailableContactDTO } from '@/api/contacts'
const contacts = ref<ContactDTO[]>([]); const loading = ref(false); const error = ref(''); const platform = ref(''); const showAttach = ref(false); const attachPlatform = ref<'wechat'|'feishu'>('wechat'); const query = ref(''); const available = ref<AvailableContactDTO[]>([]); const discovering = ref(false); const showDetail = ref(false); const detail = ref<any>(null)
const platformOptions = [{ label: '微信', value: 'wechat' }, { label: '飞书', value: 'feishu' }]
async function load() { loading.value = true; error.value = ''; try { contacts.value = await listContacts(platform.value) } catch (e: any) { error.value = e?.message || '联系人加载失败' } finally { loading.value = false } }
watch(platform, load); onMounted(load)
async function discover() { discovering.value = true; try { available.value = await discoverContacts(attachPlatform.value, query.value) } catch (e:any) { error.value = e?.message || '联系人发现失败' } finally { discovering.value = false } }
async function attach(item: AvailableContactDTO) { await attachContact({ platform: attachPlatform.value, externalUserID: item.external_user_id, displayName: item.display_name, avatarURL: item.avatar_url }); item.selected = true; await load() }
async function openDetail(contact: ContactDTO) { try { detail.value = await getContact(contact.id); showDetail.value = true } catch (e:any) { error.value = e?.message || '联系人详情加载失败' } }
async function remove() { if (!detail.value) return; await removeContact(detail.value.id); showDetail.value = false; detail.value = null; await load() }
</script>
<style scoped>
.contacts-page { padding: 28px 34px; max-width: 1180px; margin: auto; }.contacts-head { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:24px; }.contacts-head h1 { margin:0 0 8px; font-size:24px; }.contacts-head p { margin:0; color:var(--td-text-color-secondary); }.actions { display:flex; gap:10px; width:320px; }.actions .t-select { flex:1; }.contact-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(280px,1fr)); gap:14px; }.contact-card { display:flex; gap:14px; padding:18px; border:1px solid var(--td-component-stroke); border-radius:12px; background:var(--td-bg-color-container); cursor:pointer; }.avatar { flex:0 0 42px; width:42px; height:42px; display:grid; place-items:center; border-radius:50%; color:#fff; background:var(--td-brand-color); font-weight:600; }.contact-main { min-width:0; }.contact-main h3 { margin:0 0 4px; font-size:16px; }.kind { color:var(--td-text-color-secondary); font-size:12px; }.identity-list { display:grid; gap:5px; margin-top:12px; }.identity { color:var(--td-text-color-secondary); font-size:12px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }.discover-list { display:grid; gap:8px; max-height:360px; overflow:auto; }.discover-item { display:flex; align-items:center; gap:10px; padding:8px; border-bottom:1px solid var(--td-component-stroke); }.discover-item span { flex:1; }.discover-item small { color:var(--td-text-color-secondary); }.state { padding:80px 0; text-align:center; color:var(--td-text-color-secondary); }.empty { display:grid; gap:10px; place-items:center; }.empty svg { width:36px; height:36px; color:var(--td-brand-color); } @media(max-width:700px){.contacts-page{padding:20px 16px}.contacts-head{display:block}.actions{margin-top:14px;width:100%}}
</style>
