from __future__ import annotations

from typing import Any, Protocol

from app.domain.rag import (
    AccessCheck,
    AuthorizationScope,
    BranchMatch,
    Chunk,
    Entity,
    EntityAlias,
    ResourceContext,
    SearchRequest,
    SearchResult,
)


class TaskRepository(Protocol):
    def create_or_get_job(self, envelope: dict[str, Any], *, processing_version: str | None = None) -> dict[str, Any]: ...
    def get_job(self, job_id: str | None = None, *, source_event_id: str | None = None) -> dict[str, Any] | None: ...
    def claim_jobs(self, lane: str, *, limit: int = 1, lease_seconds: int | None = None) -> list[dict[str, Any]]: ...
    def heartbeat(self, job_id: str, *, lease_seconds: int | None = None) -> None: ...
    def update_job(self, job_id: str, **fields: Any) -> None: ...
    def add_attempt(self, job_id: str, **fields: Any) -> str: ...


class SourceSnapshotRepository(Protocol):
    def upsert_snapshot(self, context: ResourceContext) -> str: ...


class ChunkRepository(Protocol):
    def upsert_chunks(self, chunks: list[Chunk]) -> int: ...
    def list_chunks(self, **filters: Any) -> list[Chunk]: ...
    def update_embedding_status(self, chunk_ids: list[str], **values: Any) -> None: ...
    def mark_older_chunks_inactive(self, *, knowledge_item_id: str, content_version: int) -> None: ...


class ProjectionRepository(Protocol):
    def upsert_projection(self, chunk: Chunk, **values: Any) -> None: ...


class OutboxRepository(Protocol):
    def add_outbox_event(self, event: dict[str, Any]) -> str: ...
    def pending_outbox(self, *, limit: int = 50) -> list[dict[str, Any]]: ...
    def mark_outbox_published(self, event_id: str) -> None: ...
    def mark_outbox_failed(self, event_id: str, error: str) -> None: ...


class EntityRegistryRepository(Protocol):
    def load_entity_registry(self, *, scope_type: str, scope_id: str) -> tuple[list[Entity], list[EntityAlias], int]: ...
    def upsert_candidate_mention(self, **values: Any) -> str: ...
    def list_candidates(self, **filters: Any) -> tuple[list[dict[str, Any]], int]: ...
    def get_candidate(self, **filters: Any) -> dict[str, Any] | None: ...
    def review_candidate(self, **values: Any) -> dict[str, Any]: ...


class BranchRepository(Protocol):
    def ensure_tree_branch(self, **values: Any) -> str: ...
    def replace_chunk_branches(self, chunk: Chunk, branches: list[BranchMatch]) -> None: ...
    def get_tree(self, *, scope_type: str, scope_id: str) -> dict[str, Any]: ...


class SearchHistoryRepository(Protocol):
    def record_search(self, **values: Any) -> None: ...


class QAHistoryRepository(Protocol):
    def create_qa_conversation(self, **values: Any) -> str: ...
    def add_qa_message(self, **values: Any) -> str: ...
    def list_qa_conversations(self, *, user_id: str, page: int, page_size: int) -> tuple[list[dict[str, Any]], int]: ...
    def get_qa_conversation(self, *, user_id: str, conversation_id: str) -> dict[str, Any] | None: ...
    def rename_qa_conversation(self, *, user_id: str, conversation_id: str, title: str) -> bool: ...
    def delete_qa_conversation(self, *, user_id: str, conversation_id: str) -> bool: ...


class KnowledgeSource(Protocol):
    def get_knowledge(
        self,
        knowledge_item_id: str,
        *,
        content_version: int | None = None,
        acl_version: int | None = None,
        purpose: str | None = None,
    ) -> dict[str, Any]: ...
    def get_content(
        self,
        knowledge_item_id: str,
        *,
        content_version: int | None = None,
        acl_version: int | None = None,
        content_variant: str | None = None,
        purpose: str | None = None,
    ) -> dict[str, Any]: ...
    def get_attachment(
        self,
        attachment_id: str,
        *,
        content_version: int | None = None,
        acl_version: int | None = None,
        purpose: str | None = None,
    ) -> dict[str, Any]: ...


class EmbeddingProvider(Protocol):
    model: str
    dimensions: int

    def embed(self, texts: list[str]) -> list[list[float]]: ...


class SearchIndexer(Protocol):
    def create_indices(self) -> list[str]: ...
    def index_chunks(self, chunks: list[Chunk]) -> int: ...
    def delete_older_versions(self, *, resource_id: str, content_version: int) -> int: ...
    def search_bm25(self, request: SearchRequest, *, branch_keys: tuple[str, ...] = ()) -> list[SearchResult]: ...
    def search_knn(self, request: SearchRequest, query_vector: list[float], *, branch_keys: tuple[str, ...] = ()) -> list[SearchResult]: ...


class AuthorizationGateway(Protocol):
    def search_scope(
        self,
        *,
        user_id: str,
        scope_type: str,
        scope_id: str,
        resource_parts: tuple[str, ...],
    ) -> AuthorizationScope: ...
    def check_batch(
        self,
        *,
        user_id: str,
        scope_type: str,
        scope_id: str,
        checks: list[AccessCheck],
        snapshot_id: str | None = None,
    ) -> list[bool]: ...


class CallbackPublisher(Protocol):
    def send(self, payload: dict[str, Any]) -> None: ...
